language: python
python:
- 3.8
- 3.7
- 3.6
install:
    - pip install -U importlib_metadata
    - pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: "__token__"
  password:
    secure: bWFwxVqYcJ881R8sYGZwEXh0m3KB2ACQQ+dPApDoidVU4WEgXPAUwAcgkug6dZ4OoXPVDSbWm9ov5qHXEI8p7Y7Nej7kI5rzQoPDpo/qFSrbeVwyWMD9A22HeHz25H8hgSR7RHhzOlv39pwcMiIYPrjtL5f166hOb8k2jZMeDY1XGAaAgvuGSnRvTM75R7Js4imLwElvUaNsenpoZU3sf2XFb4DefiWSEUIsEfWyR0FRq3IiQ4O6bUupN6l6/Ay5iK5jEtLHWTNLZ/LTF0Bcavosio6ZKobZRYqxkcSP/0u4MhihnJ4rAbmLyh7rdTVewv2rjVj1PimxReqJH4lsossSHMGqgydw6U1HQaws8/JXliNvbFiTtps9ON2C1hvK56UDTQ8nQeyxkrhkEaOujxbt0XCfxOCp2+NKHZXaVL3AYHZcZZDuxJ7ijnik6WEIwJXDQb+et1t9eikHHzpB9wRR1I4BrQjQmlGLfY3vRjZfFUH7SDvdASrpIPXRVvaY1F8QSWh4z3YhG2rmDCTTiVM2U6CwdsArphSyERijxJPX9WE7cX7M704vnq6DBXW0gZFiXShiJEMjrec6/xiS8+gzfrEp69EZB8C+ED19OTS/QKXUlzddAyHmFuWLS1qnkKsJ1ze6ZgDCUarVFAZ2qMOum4PqABUxDoEsgBpzg8w=
  on:
    tags: true
    repo: phongnt570/html-reporter
    python: 3.8
